/* This file was autogenerated by ctest; do not modify directly */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include <hierarchy.h>

typedef void (*ctest_void_func)(void);

static bool ctest_const_ON_val_static = ON;

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
bool *ctest_const__ON(void) {
    return &ctest_const_ON_val_static;
}

// Return the size of a type.
uint64_t ctest_size_of__in6_addr(void) { return sizeof(in6_addr); }

// Return the alignment of a type.
uint64_t ctest_align_of__in6_addr(void) { return _Alignof(in6_addr); }

// Return `1` if the type is signed, otherwise return `0`.
// Casting -1 to the aliased type if signed evaluates to `-1 < 0`, if unsigned to `MAX_VALUE < 0`
uint32_t ctest_signededness_of__in6_addr(void) {
    in6_addr all_ones = (in6_addr) -1;
    return all_ones < 0;
}

#ifdef _MSC_VER
// Disable signed/unsigned conversion warnings on MSVC.
// These trigger even if the conversion is explicit.
#  pragma warning(disable:4365)
#endif

// Tests whether the struct/union/alias `x` when passed by value to C and back to Rust
// remains unchanged.
// It checks if the size is the same as well as if the padding bytes are all in the correct place.
in6_addr ctest_roundtrip__in6_addr(
    in6_addr value,
    const uint8_t is_padding_byte[sizeof(in6_addr)],
    uint8_t value_bytes[sizeof(in6_addr)]
) {
    int size = (int)sizeof(in6_addr);
    // Mark `p` as volatile so that the C compiler does not optimize away the pattern we create.
    // Otherwise the Rust side would not be able to see it.
    volatile uint8_t* p = (volatile uint8_t*)&value;
    int i = 0;
    for (i = 0; i < size; ++i) {
        // We skip padding bytes in both Rust and C because writing to it is undefined.
        // Instead we just make sure the the placement of the padding bytes remains the same.
        if (is_padding_byte[i]) { continue; }
        value_bytes[i] = p[i];
        // After we check that the pattern remained unchanged from Rust to C, we invert the pattern
        // and send it back to Rust to make sure that it remains unchanged from C to Rust.
        uint8_t d = (uint8_t)(255) - (uint8_t)(i % 256);
        d = d == 0 ? 42: d;
        p[i] = d;
    }
    return value;
}

#ifdef _MSC_VER
#  pragma warning(default:4365)
#endif

#ifdef _MSC_VER
// Disable function pointer type conversion warnings on MSVC.
// The conversion may fail only if we call that function, however we only check its address.
#  pragma warning(disable:4191)
#endif

ctest_void_func ctest_foreign_fn__malloc(void) {
    return (ctest_void_func)malloc;
}

#ifdef _MSC_VER
#  pragma warning(default:4191)
#endif
