/* This file was autogenerated by ctest; do not modify directly */

/// As this file is sometimes built using rustc, crate level attributes
/// are not allowed at the top-level, so we hack around this by keeping it
/// inside of a module.
mod generated_tests {
    #![allow(non_snake_case)]
    #![deny(improper_ctypes_definitions)]
    #[allow(unused_imports)]
    use std::ffi::{CStr, c_int, c_char};
    use std::fmt::{Debug, LowerHex};
    use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
    #[allow(unused_imports)]
    use std::{mem, ptr, slice};
    #[allow(unused_imports)]
    use std::mem::{MaybeUninit, offset_of};

    use super::*;

    pub static FAILED: AtomicBool = AtomicBool::new(false);
    pub static NTESTS: AtomicUsize = AtomicUsize::new(0);

    /// Check that the value returned from the Rust and C side in a certain test is equivalent.
    ///
    /// Internally it will remember which checks failed and how many tests have been run.
    fn check_same<T: PartialEq + Debug>(rust: T, c: T, attr: &str) {
        if rust != c {
            eprintln!("bad {attr}: rust: {rust:?} != c {c:?}");
            FAILED.store(true, Ordering::Relaxed);
        } else {
            NTESTS.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Check that the value returned from the Rust and C side in a certain test is equivalent.
    ///
    /// Internally it will remember which checks failed and how many tests have been run. This
    /// method is the same as `check_same` but prints errors in bytes in hex.
    fn check_same_hex<T: PartialEq + LowerHex + Debug>(rust: T, c: T, attr: &str) {
        if rust != c {
            eprintln!("bad {attr}: rust: {rust:?} ({rust:#x}) != c {c:?} ({c:#x})");
            FAILED.store(true, Ordering::Relaxed);
        } else {
            NTESTS.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Compare the size and alignment of the type in Rust and C, making sure they are the same.
    pub fn ctest_size_align_VecU8() {
        extern "C" {
            fn ctest_size_of__VecU8() -> u64;
            fn ctest_align_of__VecU8() -> u64;
        }

        let rust_size = size_of::<VecU8>() as u64;
        let c_size = unsafe { ctest_size_of__VecU8() };

        let rust_align = align_of::<VecU8>() as u64;
        let c_align = unsafe { ctest_align_of__VecU8() };

        check_same(rust_size, c_size, "VecU8 size");
        check_same(rust_align, c_align, "VecU8 align");
    }

    /// Compare the size and alignment of the type in Rust and C, making sure they are the same.
    pub fn ctest_size_align_VecU16() {
        extern "C" {
            fn ctest_size_of__VecU16() -> u64;
            fn ctest_align_of__VecU16() -> u64;
        }

        let rust_size = size_of::<VecU16>() as u64;
        let c_size = unsafe { ctest_size_of__VecU16() };

        let rust_align = align_of::<VecU16>() as u64;
        let c_align = unsafe { ctest_align_of__VecU16() };

        check_same(rust_size, c_size, "VecU16 size");
        check_same(rust_align, c_align, "VecU16 align");
    }

    /// Generates a padding map for a specific type.
    ///
    /// Essentially, it returns a list of bytes, whose length is equal to the size of the type in
    /// bytes. Each element corresponds to a byte and has two values. `true` if the byte is padding,
    /// and `false` if the byte is not padding.
    ///
    /// For aliases we assume that there are no padding bytes, for structs and unions,
    /// if there are no fields, then everything is padding, if there are fields, then we have to
    /// go through each field and figure out the padding.
    fn roundtrip_padding__VecU8() -> Vec<bool> {
        // FIXME(ctest): What if it's an alias to a struct/union?
        vec![!false; size_of::<VecU8>()]
    }

    /// Tests whether the type alias `x` when passed to C and back to Rust remains unchanged.
    ///
    /// It checks if the size is the same as well as if the padding bytes are all in the
    /// correct place.
    pub fn ctest_roundtrip_VecU8() {
        type U = VecU8;
        extern "C" {
            fn ctest_size_of__VecU8() -> u64;
            fn ctest_roundtrip__VecU8(
                x: MaybeUninit<U>, e: *mut c_int, pad: *const bool, expected: *mut u8
            ) -> U;
        }
        let pad = roundtrip_padding__VecU8();
        let mut error: c_int = 0;
        let mut y = MaybeUninit::<U>::zeroed();
        let mut x = MaybeUninit::<U>::zeroed();

        let x_ptr = x.as_mut_ptr().cast::<u8>();
        let y_ptr = y.as_mut_ptr().cast::<u8>();
        let size = size_of::<U>();

        // Fill the unitialized memory with a deterministic pattern.
        // From Rust to C: every byte will be labelled from 1 to 255, with 0 turning into 42.
        // From C to Rust: every byte will be inverted from before (254 -> 1), but 0 is still 42.
        for i in 0..size {
            let c: u8 = (i % 256) as u8;
            let c = if c == 0 { 42 } else { c };
            let d: u8 = 255_u8 - (i % 256) as u8;
            let d = if d == 0 { 42 } else { d };
            unsafe {
                x_ptr.add(i).write_volatile(c);
                y_ptr.add(i).write_volatile(d);
            }
        }

        let c_size = unsafe { ctest_size_of__VecU8() } as usize;
        if size != c_size {
            FAILED.store(true, Ordering::Relaxed);
            eprintln!(
                "size of struct VecU8 is {c_size} in C and {size} in Rust\n",
            );
            return;
        }

        let mut expected = vec![0; size_of::<VecU8>()];
        let r: U = unsafe {
            ctest_roundtrip__VecU8(x, &mut error, pad.as_ptr(), expected.as_mut_ptr())
        };

        for (i, elem) in pad.iter().enumerate().take(size) {
            if *elem { continue; }
            let rust = unsafe { *x_ptr.add(i) };
            let c = expected[i];
            if rust != c {
                eprintln!("rust[{}] = {} != {} (C): Rust \"VecU8\" -> C", i, rust, c);
                FAILED.store(true, Ordering::Relaxed);
            }
        }

        for (i, elem) in pad.iter().enumerate().take(size) {
            if *elem { continue; }
            let rust = unsafe { (*y_ptr.add(i)) as usize };
            let c = unsafe { (&raw const r).cast::<u8>().add(i).read_volatile() as usize };
            if rust != c {
                eprintln!(
                    "rust [{i}] = {rust} != {c} (C): C \"VecU8\" -> Rust",
                );
                FAILED.store(true, Ordering::Relaxed);
            }
        }
    }

    /// Generates a padding map for a specific type.
    ///
    /// Essentially, it returns a list of bytes, whose length is equal to the size of the type in
    /// bytes. Each element corresponds to a byte and has two values. `true` if the byte is padding,
    /// and `false` if the byte is not padding.
    ///
    /// For aliases we assume that there are no padding bytes, for structs and unions,
    /// if there are no fields, then everything is padding, if there are fields, then we have to
    /// go through each field and figure out the padding.
    fn roundtrip_padding__VecU16() -> Vec<bool> {
        // FIXME(ctest): What if it's an alias to a struct/union?
        vec![!false; size_of::<VecU16>()]
    }

    /// Tests whether the type alias `x` when passed to C and back to Rust remains unchanged.
    ///
    /// It checks if the size is the same as well as if the padding bytes are all in the
    /// correct place.
    pub fn ctest_roundtrip_VecU16() {
        type U = VecU16;
        extern "C" {
            fn ctest_size_of__VecU16() -> u64;
            fn ctest_roundtrip__VecU16(
                x: MaybeUninit<U>, e: *mut c_int, pad: *const bool, expected: *mut u8
            ) -> U;
        }
        let pad = roundtrip_padding__VecU16();
        let mut error: c_int = 0;
        let mut y = MaybeUninit::<U>::zeroed();
        let mut x = MaybeUninit::<U>::zeroed();

        let x_ptr = x.as_mut_ptr().cast::<u8>();
        let y_ptr = y.as_mut_ptr().cast::<u8>();
        let size = size_of::<U>();

        // Fill the unitialized memory with a deterministic pattern.
        // From Rust to C: every byte will be labelled from 1 to 255, with 0 turning into 42.
        // From C to Rust: every byte will be inverted from before (254 -> 1), but 0 is still 42.
        for i in 0..size {
            let c: u8 = (i % 256) as u8;
            let c = if c == 0 { 42 } else { c };
            let d: u8 = 255_u8 - (i % 256) as u8;
            let d = if d == 0 { 42 } else { d };
            unsafe {
                x_ptr.add(i).write_volatile(c);
                y_ptr.add(i).write_volatile(d);
            }
        }

        let c_size = unsafe { ctest_size_of__VecU16() } as usize;
        if size != c_size {
            FAILED.store(true, Ordering::Relaxed);
            eprintln!(
                "size of struct VecU16 is {c_size} in C and {size} in Rust\n",
            );
            return;
        }

        let mut expected = vec![0; size_of::<VecU16>()];
        let r: U = unsafe {
            ctest_roundtrip__VecU16(x, &mut error, pad.as_ptr(), expected.as_mut_ptr())
        };

        for (i, elem) in pad.iter().enumerate().take(size) {
            if *elem { continue; }
            let rust = unsafe { *x_ptr.add(i) };
            let c = expected[i];
            if rust != c {
                eprintln!("rust[{}] = {} != {} (C): Rust \"VecU16\" -> C", i, rust, c);
                FAILED.store(true, Ordering::Relaxed);
            }
        }

        for (i, elem) in pad.iter().enumerate().take(size) {
            if *elem { continue; }
            let rust = unsafe { (*y_ptr.add(i)) as usize };
            let c = unsafe { (&raw const r).cast::<u8>().add(i).read_volatile() as usize };
            if rust != c {
                eprintln!(
                    "rust [{i}] = {rust} != {c} (C): C \"VecU16\" -> Rust",
                );
                FAILED.store(true, Ordering::Relaxed);
            }
        }
    }
}

use generated_tests::*;

fn main() {
    println!("RUNNING ALL TESTS");
    run_all();
    if FAILED.load(std::sync::atomic::Ordering::Relaxed) {
        panic!("some tests failed");
    } else {
        println!(
            "PASSED {} tests",
            NTESTS.load(std::sync::atomic::Ordering::Relaxed)
        );
    }
}

// Run all tests by calling the functions that define them.
fn run_all() {
    ctest_size_align_VecU8();
    ctest_size_align_VecU16();
    ctest_roundtrip_VecU8();
    ctest_roundtrip_VecU16();
}
