/* This file was autogenerated by ctest; do not modify directly */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <simple.h>

static char const* __test_const_A_val = A;

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
char const** __test_const_A(void) {
    return &__test_const_A_val;
}

static char const* __test_const_B_val = C_B;

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
char const** __test_const_B(void) {
    return &__test_const_B_val;
}
