/* This file was autogenerated by ctest; do not modify directly */

/// As this file is sometimes built using rustc, crate level attributes
/// are not allowed at the top-level, so we hack around this by keeping it
/// inside of a module.
mod generated_tests {
    #![allow(non_snake_case)]
    #![deny(improper_ctypes_definitions)]
    use std::ffi::CStr;
    use std::fmt::{Debug, LowerHex};
    use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
    use std::{mem, ptr, slice};

    use super::*;

    pub static FAILED: AtomicBool = AtomicBool::new(false);
    pub static NTESTS: AtomicUsize = AtomicUsize::new(0);

    /// Check that the value returned from the Rust and C side in a certain test is equivalent.
    ///
    /// Internally it will remember which checks failed and how many tests have been run.
    fn check_same<T: PartialEq + Debug>(rust: T, c: T, attr: &str) {
        if rust != c {
            eprintln!("bad {attr}: rust: {rust:?} != c {c:?}");
            FAILED.store(true, Ordering::Relaxed);
        } else {
            NTESTS.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Check that the value returned from the Rust and C side in a certain test is equivalent.
    ///
    /// Internally it will remember which checks failed and how many tests have been run. This
    /// method is the same as `check_same` but prints errors in bytes in hex.
    fn check_same_hex<T: PartialEq + LowerHex + Debug>(rust: T, c: T, attr: &str) {
        if rust != c {
            eprintln!("bad {attr}: rust: {rust:?} ({rust:#x}) != c {c:?} ({c:#x})");
            FAILED.store(true, Ordering::Relaxed);
        } else {
            NTESTS.fetch_add(1, Ordering::Relaxed);
        }
    }

    // Test that the string constant is the same in both Rust and C.
    // While fat pointers can't be translated, we instead use * const c_char.
    pub fn ctest_const_cstr_A() {
        extern "C" {
            fn ctest_const_cstr__A() -> *const c_char;
        }

        // SAFETY: we assume that `c_char` pointer consts are for C strings.
        let r_val = unsafe {
            let r_ptr: *const c_char = A;
            assert!(!r_ptr.is_null(), "const A is null");
            CStr::from_ptr(r_ptr)
        };

        // SAFETY: FFI call returns a valid C string.
        let c_val = unsafe {
            let c_ptr: *const c_char = unsafe { ctest_const_cstr__A()  };
            CStr::from_ptr(c_ptr)
        };

        check_same(r_val, c_val, "const A string");
    }

    // Test that the string constant is the same in both Rust and C.
    // While fat pointers can't be translated, we instead use * const c_char.
    pub fn ctest_const_cstr_B() {
        extern "C" {
            fn ctest_const_cstr__B() -> *const c_char;
        }

        // SAFETY: we assume that `c_char` pointer consts are for C strings.
        let r_val = unsafe {
            let r_ptr: *const c_char = B;
            assert!(!r_ptr.is_null(), "const B is null");
            CStr::from_ptr(r_ptr)
        };

        // SAFETY: FFI call returns a valid C string.
        let c_val = unsafe {
            let c_ptr: *const c_char = unsafe { ctest_const_cstr__B()  };
            CStr::from_ptr(c_ptr)
        };

        check_same(r_val, c_val, "const B string");
    }

    /// Compare the size and alignment of the type in Rust and C, making sure they are the same.
    pub fn ctest_size_align_Byte() {
        extern "C" {
            fn ctest_size_of__Byte() -> u64;
            fn ctest_align_of__Byte() -> u64;
        }

        let rust_size = size_of::<Byte>() as u64;
        let c_size = unsafe { ctest_size_of__Byte() };

        let rust_align = align_of::<Byte>() as u64;
        let c_align = unsafe { ctest_align_of__Byte() };

        check_same(rust_size, c_size, "Byte size");
        check_same(rust_align, c_align, "Byte align");
    }

    /// Compare the size and alignment of the type in Rust and C, making sure they are the same.
    pub fn ctest_size_align_Person() {
        extern "C" {
            fn ctest_size_of__Person() -> u64;
            fn ctest_align_of__Person() -> u64;
        }

        let rust_size = size_of::<Person>() as u64;
        let c_size = unsafe { ctest_size_of__Person() };

        let rust_align = align_of::<Person>() as u64;
        let c_align = unsafe { ctest_align_of__Person() };

        check_same(rust_size, c_size, "Person size");
        check_same(rust_align, c_align, "Person align");
    }

    /// Compare the size and alignment of the type in Rust and C, making sure they are the same.
    pub fn ctest_size_align_Word() {
        extern "C" {
            fn ctest_size_of__Word() -> u64;
            fn ctest_align_of__Word() -> u64;
        }

        let rust_size = size_of::<Word>() as u64;
        let c_size = unsafe { ctest_size_of__Word() };

        let rust_align = align_of::<Word>() as u64;
        let c_align = unsafe { ctest_align_of__Word() };

        check_same(rust_size, c_size, "Word size");
        check_same(rust_align, c_align, "Word align");
    }

    /// Make sure that the signededness of a type alias in Rust and C is the same.
    ///
    /// This is done by casting 0 to that type and flipping all of its bits. For unsigned types,
    /// this would result in a value larger than zero. For signed types, this results in a value
    /// smaller than 0.
    pub fn ctest_signededness_Byte() {
         extern "C" {
            fn ctest_signededness_of__Byte() -> u32;
        }
        let all_ones = !(0 as Byte);
        let all_zeros = 0 as Byte;
        let c_is_signed = unsafe { ctest_signededness_of__Byte() };

        check_same((all_ones < all_zeros) as u32, c_is_signed, "Byte signed");
    }
}

use generated_tests::*;

fn main() {
    println!("RUNNING ALL TESTS");
    run_all();
    if FAILED.load(std::sync::atomic::Ordering::Relaxed) {
        panic!("some tests failed");
    } else {
        println!(
            "PASSED {} tests",
            NTESTS.load(std::sync::atomic::Ordering::Relaxed)
        );
    }
}

// Run all tests by calling the functions that define them.
fn run_all() {
    ctest_const_cstr_A();
    ctest_const_cstr_B();
    ctest_size_align_Byte();
    ctest_size_align_Person();
    ctest_size_align_Word();
    ctest_signededness_Byte();
}
