/* This file was autogenerated by ctest; do not modify directly */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include <simple.h>

static char const* ctest_const_A_val_static = A;

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
char const** __ctest_const_cstr_A(void) {
    return &ctest_const_A_val_static;
}
