task:
  name: nightly x86_64-unknown-freebsd-12
  freebsd_instance:
    image: freebsd-12-4-release-amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain nightly -y --profile=minimal
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - LIBC_CI=1 sh ci/run.sh x86_64-unknown-freebsd
    - sh ci/run.sh x86_64-unknown-freebsd

task:
  name: nightly x86_64-unknown-freebsd-13
  freebsd_instance:
    image: freebsd-13-1-release-amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain nightly --profile=minimal
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - LIBC_CI=1 sh ci/run.sh x86_64-unknown-freebsd
    - sh ci/run.sh x86_64-unknown-freebsd

task:
  name: nightly x86_64-unknown-freebsd-14
  freebsd_instance:
    image: freebsd-14-0-current-amd64-v20230114
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain nightly --profile=minimal
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - LIBC_CI=1 sh ci/run.sh x86_64-unknown-freebsd
    - sh ci/run.sh x86_64-unknown-freebsd
