name: CI (macOS)

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - beta
          - nightly
        target:
          - x86_64-apple-darwin

    name: ${{ matrix.version }} - ${{ matrix.target }}
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.version }}
        run: TOOLCHAIN=${{ matrix.version }} TARGET=${{ matrix.target }} sh ./ci/install-rust.sh

      - name: Run tests
        run: cargo test --all -- --nocapture

      - name: Run libc tests
        env:
          TARGET: ${{ matrix.target }}
        run: sh ./ci/run.sh ${{ matrix.target }}
