/* This file was autogenerated by ctest; do not modify directly */
{#- ↑ Doesn't apply here, this is the template! +#}

{%- let ctx = self.template +%}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

{%- for header in self.headers +%}

#include <{{ header }}>
{%- endfor +%}

{%- for const_cstr in ctx.const_cstr_tests +%}

static {{ const_cstr.c_type }} ctest_const_{{ const_cstr.rust_ident }}_val_static = {{ const_cstr.c_ident }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
{{ const_cstr.c_type }}* __{{ const_cstr.test_ident }}(void) {
    return &ctest_const_{{ const_cstr.rust_ident }}_val_static;
}
{%- endfor +%}

{%- for constant in ctx.const_tests +%}

static {{ constant.c_type }} ctest_const_{{ constant.rust_ident }}_val_static = {{ constant.c_ident }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
{{ constant.c_type }}* __{{ constant.test_ident }}(void) {
    return &ctest_const_{{ constant.rust_ident }}_val_static;
}
{%- endfor +%}

