/* This file was autogenerated by ctest; do not modify directly */
{#- ↑ Doesn't apply here, this is the template! +#}

{%- let ctx = self.template +%}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

{%- for header in self.headers +%}

#include <{{ header }}>
{%- endfor +%}

{%- for const_cstr in ctx.const_cstr_tests +%}

static char *ctest_const_{{ const_cstr.id }}_val_static = {{ const_cstr.c_val }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
char *ctest_const_cstr__{{ const_cstr.id }}(void) {
    return ctest_const_{{ const_cstr.id }}_val_static;
}
{%- endfor +%}

{%- for constant in ctx.const_tests +%}

static {{ constant.c_ty }} ctest_const_{{ constant.id }}_val_static = {{ constant.c_val }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
{{ constant.c_ty }} *ctest_const__{{ constant.id }}(void) {
    return &ctest_const_{{ constant.id }}_val_static;
}
{%- endfor +%}
