/* This file was autogenerated by ctest; do not modify directly */
{#- ↑ Doesn't apply here, this is the template! +#}

{%- let ctx = self.template +%}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

{%- for header in self.headers +%}

#include <{{ header }}>
{%- endfor +%}

{%- for const_cstr in ctx.const_cstr_tests +%}

static char *ctest_const_{{ const_cstr.id }}_val_static = {{ const_cstr.c_val }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
char *ctest_const_cstr__{{ const_cstr.id }}(void) {
    return ctest_const_{{ const_cstr.id }}_val_static;
}
{%- endfor +%}

{%- for constant in ctx.const_tests +%}

static {{ constant.c_ty }} ctest_const_{{ constant.id }}_val_static = {{ constant.c_val }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
{{ constant.c_ty }} *ctest_const__{{ constant.id }}(void) {
    return &ctest_const_{{ constant.id }}_val_static;
}
{%- endfor +%}

{%- for item in ctx.size_align_tests +%}

// Return the size of a type.
uint64_t ctest_size_of__{{ item.id }}(void) { return sizeof({{ item.c_ty }}); }

// Return the alignment of a type.
uint64_t ctest_align_of__{{ item.id }}(void) { return _Alignof({{ item.c_ty }}); }
{%- endfor +%}

{%- for alias in ctx.signededness_tests +%}

// Return `1` if the type is signed, otherwise return `0`.
// Casting -1 to the aliased type if signed evaluates to `-1 < 0`, if unsigned to `MAX_VALUE < 0`
uint32_t ctest_signededness_of__{{ alias.id }}(void) {
    {{ alias.c_ty }} all_ones = ({{ alias.c_ty }}) -1;
    return all_ones < 0;
}
{%- endfor +%}
