language: rust

matrix:
  fast_finish: true
  include:
    - name: "nightly (x86_64-unknown-linux-gnu) + libc-test + tools + docs"
      rust: nightly
      after_script:
        - ci/run-docker.sh x86_64-unknown-linux-gnu
        - |
          if rustup component add rustfmt-preview ; then
              cargo fmt --all -- --check
          fi
        - |
          if rustup component add clippy-preview ; then
            cargo clippy -- -D clippy::pedantic
          fi
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master
    - name: "nightly (x86_64-apple-darwin) + libc-test"
      rust: nightly
      os: osx
      osx_image: xcode9.4
      after_script:
        - git clone https://github.com/rust-lang/libc
        - sed -i '' 's@ctest = "0.2"@ctest = { path = "../.." }@g' libc/libc-test/Cargo.toml
        - cd libc
        - cargo generate-lockfile --manifest-path libc-test/Cargo.toml
        - |
          export TARGET=x86_64-apple-darwin
          sh ci/run.sh $TARGET
    - name: "stable (x86_64-unknown-linux-gnu)"
      rust: stable
    - name: "beta (x86_64-unknown-linux-gnu)"
      rust: beta

script:
  - cargo test
  - cargo test --manifest-path testcrate/Cargo.toml

notifications:
  email:
    on_success: never
