language: rust

matrix:
  fast_finish: true
  include:
    - name: "nightly (x86_64-unknown-linux-gnu) + libc-test + tools + docs"
      rust: nightly
      after_script:
        - ci/run-docker.sh x86_64-unknown-linux-gnu
        - |
          if rustup component add rustfmt-preview ; then
              cargo fmt --all -- --check
          fi
        - |
          if rustup component add clippy-preview ; then
            cargo clippy -- -D clippy::pedantic
          fi
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master
    - name: "nightly (x86_64-apple-darwin) + libc-test"
      env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
      osx_image: xcode10
      after_script: sh ci/run.sh $TARGET
    - name: "nightly (i686-apple-darwin) + libc-test"
      env: TARGET=i686-apple-darwin
      rust: nightly
      os: osx
      osx_image: xcode10
      after_script: sh ci/run.sh $TARGET
    - name: "stable (x86_64-unknown-linux-gnu)"
      rust: stable
    - name: "beta (x86_64-unknown-linux-gnu)"
      rust: beta

script:
  - cargo test --all
  - cargo test --all --release

notifications:
  email:
    on_success: never
