[package]
name = "ctest-test"
version = "0.1.0"
publish = false
edition = "2021"
rust-version = "1.88"

[build-dependencies]
ctest = { path = "../ctest" }
# FIXME: Unpin once https://github.com/rust-lang/cc-rs/pull/1845 is released.
cc = "=1.4.0"

[dev-dependencies]
ctest = { path = "../ctest" }

[dependencies]
libc = { path = ".." }

[[bin]]
name = "t1"
test = false

[[bin]]
name = "t2"
test = false

[lints]
workspace = true
