name: CI
permissions: {}

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # Run CI on `main` daily so there is a cache available for merge queues.
    # See <https://github.com/orgs/community/discussions/66430>
    - cron: "0 8 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true
  LIBC_BUILD_VERBOSE: true
  LIBC_CI: 1
  RUSTDOCFLAGS: -Dwarnings
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full
  # Base branch for PRs or for merges, current ref for cron runs on a branch.
  TARGET_REF: ${{ github.base_ref || github.event.merge_group.base_ref || github.ref }}

defaults:
  run:
    shell: bash

jobs:
  style_check:
    name: Style check
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Rust toolchain
        run: ./ci/install-rust.sh && rustup component add rustfmt
      - name: Check style
        run: ./ci/style.py

  clippy:
    name: Clippy on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04, macos-26, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: rustup update stable --no-self-update
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      # Here we use the latest stable Rust toolchain already installed by GitHub
      # Ideally we should run it for every target, but we cannot rely on unstable toolchains
      # due to Clippy not being consistent between them.
      - run: cargo clippy --workspace --exclude libc-test --exclude ctest-test --all-targets -- -D warnings

  test_tier2_vm:
    name: Test tier2 VM
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: "15.0"
            target: i686-unknown-freebsd
          - release: "14.4"
            target: x86_64-unknown-freebsd
          - release: "15.0"
            target: x86_64-unknown-freebsd
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Test on FreeBSD
        uses: vmactions/freebsd-vm@77ed28d336d03fe19a3f4f7266c1d2c4714dd79d # v1.5.2
        if: contains(matrix.target, 'freebsd')
        with:
          release: ${{ matrix.release }}
          envs: CARGO_TERM_COLOR CARGO_TERM_VERBOSE RUSTDOCFLAGS RUSTFLAGS RUST_BACKTRACE
          usesh: true
          copyback: false
          prepare: ./ci/bsd-prepare.sh ${{ matrix.target }}
          run: |
            set -ex
            . "$HOME/.cargo/env"
            LIBC_CI=1 ./ci/run.sh ${{ matrix.target }}
            ./ci/run.sh ${{ matrix.target }}

      - name: Test on Solaris
        uses: vmactions/solaris-vm@315163f088b66e55bbcc45928bd224d4973b2312 # v1.3.8
        if: contains(matrix.target, 'solaris')
        with:
          release: "11.4-gcc"
          envs: CARGO_TERM_COLOR CARGO_TERM_VERBOSE RUSTDOCFLAGS RUSTFLAGS RUST_BACKTRACE
          usesh: true
          mem: 4096
          copyback: false
          prepare: ./ci/bsd-prepare.sh ${{ matrix.target }}
          run: ./ci/bsd-run.sh ${{ matrix.target }}

      - name: Test on NetBSD
        uses: vmactions/netbsd-vm@e7ac71b97abbe8437cec8859a5acf72dfa6a8be0 # v1.4.5
        if: contains(matrix.target, 'netbsd')
        with:
          release: "10.1"
          envs: CARGO_TERM_COLOR CARGO_TERM_VERBOSE RUSTDOCFLAGS RUSTFLAGS RUST_BACKTRACE
          usesh: true
          mem: 4096
          copyback: false
          prepare: ./ci/bsd-prepare.sh ${{ matrix.target }}
          run: ./ci/bsd-run.sh ${{ matrix.target }}

      - name: Test on illumos
        uses: vmactions/omnios-vm@027e3ec08fed6fb740ab5f300c2605f9de02997a # v1.3.4
        if: contains(matrix.target, 'illumos')
        with:
          # Use the latest LTS
          release: "r151054-build"
          envs: CARGO_TERM_COLOR CARGO_TERM_VERBOSE RUSTDOCFLAGS RUSTFLAGS RUST_BACKTRACE
          usesh: true
          mem: 4096
          copyback: false
          prepare: ./ci/bsd-prepare.sh ${{ matrix.target }}
          run: ./ci/bsd-run.sh ${{ matrix.target }}

  ctest_msrv:
    name: Check ctest MSRV
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    env:
      RUSTFLAGS: "" # No need to check warnings on old MSRV, clear `-Dwarnings`
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - run: |
        msrv="$(
          cargo metadata --format-version 1 |
          jq -r --arg CRATE_NAME ctest '.packages | map(select((.name == $CRATE_NAME) and (.id | startswith("path+file")))) | first | .rust_version'
        )"
        echo "MSRV: $msrv"
        echo "MSRV=$msrv" >> "$GITHUB_ENV"
    - name: Install Rust
      run: rustup update "$MSRV" --no-self-update && rustup default "$MSRV"
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
    - run: cargo build -p ctest

  docs:
    name: Ensure docs build
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Rust
      # FIXME(rust-lang/rust#160439): unpin once the issue is fixed
      run: rustup update nightly-2026-08-02 --no-self-update && rustup default nightly-2026-08-02
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
    - run: cargo doc --workspace --no-deps

  zizmor:
    name: Zizmor (Static analysis for GitHub Actions)
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1

  # One job that "summarizes" the success state of this pipeline. This can then be added to branch
  # protection, rather than having to add each job separately.
  success:
    name: success
    runs-on: ubuntu-26.04
    needs:
      - style_check
      - test_tier2_vm
      - ctest_msrv
      - docs
      - clippy
      - zizmor
    # GitHub branch protection is exceedingly silly and treats "jobs skipped because a dependency
    # failed" as success. So we have to do some contortions to ensure the job fails if any of its
    # dependencies fails.
    if: always() # make sure this is never "skipped"
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
      # Manually check the status of all dependencies. `if: failure()` does not work.
      - name: check if any dependency failed
        run: jq --exit-status 'all(.result == "success")' <<< "$NEEDS"
