# release-plz for the stable 0.2 branch

name: Release-plz v0.2

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - libc-0.2

jobs:
  release-plz:
    name: Release-plz v0.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Rust (rustup)
        run: rustup update stable --no-self-update && rustup default stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
